[package]
name = "ember-rs"
version = "0.1.0"
edition = "2021"
authors = ["Alan Koterba alan@koterba.dev"]
repository = "https://github.com/koterba/ember-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.24.0"